#!/usr/bin/env php
<?php

if (file_exists($autoload = __DIR__.'/../../../autoload.php')) {
    require $autoload;
} elseif (file_exists($autoload = __DIR__.'/vendor/autoload.php')) {
    // Is installed locally
    require $autoload;
} else {
    throw new RuntimeException('Unable to find the Composer autoloader.');
}

$dbdiff = new DBDiff\DBDiff;
$dbdiff->run();
