#!/usr/bin/env php
<?php

if (file_exists(__DIR__ . '/../../autoload.php')) {
    require __DIR__ . '/../../autoload.php';
} else {
    require __DIR__ . '/vendor/autoload.php';
}

use DBDiff\Migration\Command\DiffCommand;
use DBDiff\Migration\Command\MigrationNewCommand;
use DBDiff\Migration\Command\MigrationUpCommand;
use DBDiff\Migration\Command\MigrationDownCommand;
use DBDiff\Migration\Command\MigrationStatusCommand;
use DBDiff\Migration\Command\MigrationValidateCommand;
use DBDiff\Migration\Command\MigrationRepairCommand;
use DBDiff\Migration\Command\MigrationBaselineCommand;
use DBDiff\Migration\Command\UrlEncodeCommand;
use Symfony\Component\Console\Application;

$app = new Application('DBDiff', '2.0.0');

$app->addCommands([
    new DiffCommand,
    new MigrationNewCommand,
    new MigrationUpCommand,
    new MigrationDownCommand,
    new MigrationStatusCommand,
    new MigrationValidateCommand,
    new MigrationRepairCommand,
    new MigrationBaselineCommand,
    new UrlEncodeCommand,
]);

// `diff` is the default so that the legacy invocation
//   dbdiff server1.db1:server2.db2
// continues to work unchanged.
$app->setDefaultCommand('diff');

$app->run();
