<?php

use DBDiff\DB\Adapters\PostgresAdapter;
use Illuminate\Database\Capsule\Manager as Capsule;
use Illuminate\Database\Events\StatementPrepared;
use Illuminate\Events\Dispatcher;
use PHPUnit\Framework\TestCase;

/**
 * Integration tests for the batch schema fetch (issue #165) against a live
 * PostgreSQL server.
 *
 * The batch path exists purely as a faster way to obtain what the per-table
 * path already returns, so the invariant that matters is equivalence:
 * getBulkTableSchema() over N tables must produce exactly what N calls to
 * getTableSchema() produce. These tests assert that on a schema built to
 * exercise the cases batching is most likely to break — shared column names,
 * shared constraint names, and constraint-backed indexes.
 *
 * Unlike the end-to-end migration tests, this suite creates and drops its own
 * database and compares the two code paths against each other, so it needs no
 * per-version golden files.
 *
 * Skips automatically when:
 *   - pdo_pgsql is not loaded
 *   - DB_HOST_POSTGRES is not set
 */
class BulkSchemaPostgresTest extends TestCase
{
    private string $db = 'dbdiff_bulk_schema';
    private ?PDO $adminDb = null;
    private $capsule;
    private $connection;
    private PostgresAdapter $adapter;

    /**
     * Drop the scratch database, evicting any session still attached to it.
     * WITH (FORCE) needs Postgres 13+; fall back to a plain drop below that.
     */
    private function dropScratchDb(): void
    {
        try {
            $this->adminDb->exec("DROP DATABASE IF EXISTS {$this->db} WITH (FORCE)");
        } catch (PDOException $e) {
            $this->adminDb->exec("DROP DATABASE IF EXISTS {$this->db}");
        }
    }

    protected function setUp(): void
    {
        if (!extension_loaded('pdo_pgsql')) {
            $this->markTestSkipped('pdo_pgsql extension not loaded — skipping bulk schema tests.');
        }
        $host = getenv('DB_HOST_POSTGRES') ?: null;
        if (!$host) {
            $this->markTestSkipped('DB_HOST_POSTGRES env var not set — skipping bulk schema tests.');
        }

        $port = 5432;
        $user = 'dbdiff';
        $pass = 'rootpass';

        $this->adminDb = new PDO(
            "pgsql:host=$host;port=$port;dbname=diff1",
            $user,
            $pass,
            [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
        );
        $this->dropScratchDb();
        $this->adminDb->exec("CREATE DATABASE {$this->db}");

        $capsule    = new Capsule;
        $dispatcher = new Dispatcher();
        $dispatcher->listen(StatementPrepared::class, function ($event) {
            $event->statement->setFetchMode(PDO::FETCH_ASSOC);
        });
        $capsule->setEventDispatcher($dispatcher);
        $capsule->addConnection([
            'driver'   => 'pgsql',
            'host'     => $host,
            'port'     => $port,
            'database' => $this->db,
            'username' => $user,
            'password' => $pass,
            'charset'  => 'utf8',
            'schema'   => 'public',
        ], 'bulk');

        $this->capsule    = $capsule;
        $this->connection = $capsule->getConnection('bulk');
        $this->adapter    = new PostgresAdapter();

        $this->connection->unprepared(<<<'SQL'
            CREATE TABLE parent (
                id   integer PRIMARY KEY,
                code varchar(20) NOT NULL,
                CONSTRAINT parent_code_uniq UNIQUE (code)
            );

            -- Shares a column name and a constraint name with `orders` below.
            CREATE TABLE users (
                id         integer GENERATED BY DEFAULT AS IDENTITY,
                name       text NOT NULL,
                email      varchar(255),
                balance    numeric(12,2) DEFAULT 0.00,
                created_at timestamptz(3) DEFAULT now(),
                tags       text[],
                parent_id  integer,
                CONSTRAINT users_pkey2 PRIMARY KEY (id),
                CONSTRAINT shared_name FOREIGN KEY (parent_id)
                    REFERENCES parent (id) ON UPDATE CASCADE ON DELETE SET NULL,
                CONSTRAINT balance_non_negative CHECK (balance >= 0)
            );
            CREATE INDEX users_email_idx ON users (email);
            CREATE INDEX users_partial_idx ON users (name) WHERE email IS NOT NULL;

            -- Same column name (`name`) and same constraint name (`shared_name`)
            -- as `users`, which Postgres allows because both are table-scoped.
            CREATE TABLE orders (
                id      integer PRIMARY KEY,
                name    varchar(50),
                total   numeric(10,2) NOT NULL,
                qty     integer NOT NULL DEFAULT 1,
                line    numeric(10,2) GENERATED ALWAYS AS (total * qty) STORED,
                CONSTRAINT shared_name CHECK (id > 0),
                CONSTRAINT orders_total_uniq UNIQUE (id, total)
            );
            CREATE INDEX orders_total_idx ON orders (total);

            -- No indexes or constraints beyond the implicit ones.
            CREATE TABLE plain (a integer, b text);
        SQL);
    }

    protected function tearDown(): void
    {
        if ($this->adminDb === null) {
            return;
        }
        // Release the pooled PDO handle first, or the DROP blocks on it.
        if ($this->connection !== null) {
            $this->connection->disconnect();
            $this->connection = null;
        }
        $this->capsule = null;
        $this->dropScratchDb();
        $this->adminDb = null;
    }

    private const TABLES = ['parent', 'users', 'orders', 'plain'];

    // ── Equivalence with the per-table path ───────────────────────────────

    public function testBulkMatchesPerTableSchemaForEveryTable(): void
    {
        $bulk = $this->adapter->getBulkTableSchema($this->connection, self::TABLES);

        foreach (self::TABLES as $table) {
            $this->assertSame(
                $this->adapter->getTableSchema($this->connection, $table),
                $bulk[$table],
                "Batch schema for `$table` diverged from the per-table fetch"
            );
        }
    }

    public function testBulkReturnsAnEntryForEveryRequestedTable(): void
    {
        $bulk = $this->adapter->getBulkTableSchema($this->connection, self::TABLES);
        $this->assertSame(self::TABLES, array_keys($bulk));
    }

    public function testUnknownTableYieldsEmptySchemaRatherThanMissingKey(): void
    {
        $bulk = $this->adapter->getBulkTableSchema($this->connection, ['users', 'no_such_table']);

        $this->assertArrayHasKey('no_such_table', $bulk);
        $this->assertSame([], $bulk['no_such_table']['columns']);
        $this->assertSame([], $bulk['no_such_table']['keys']);
        $this->assertSame([], $bulk['no_such_table']['constraints']);
    }

    public function testSingleTableBatchMatchesFullBatch(): void
    {
        // Batch size must not change the result for a given table.
        $full = $this->adapter->getBulkTableSchema($this->connection, self::TABLES);
        foreach (self::TABLES as $table) {
            $one = $this->adapter->getBulkTableSchema($this->connection, [$table]);
            $this->assertSame($full[$table], $one[$table], "Batch size changed the result for `$table`");
        }
    }

    // ── Cross-table isolation ─────────────────────────────────────────────

    public function testSharedConstraintNameStaysScopedToItsTable(): void
    {
        // `users` and `orders` both have a constraint called `shared_name`:
        // an FK on one, a CHECK on the other. Joining pg_constraint by name
        // alone merges them and duplicates the FK's column list.
        $bulk = $this->adapter->getBulkTableSchema($this->connection, ['users', 'orders']);

        $this->assertStringContainsString(
            'FOREIGN KEY ("parent_id") REFERENCES "parent" ("id")',
            $bulk['users']['constraints']['shared_name']
        );
        $this->assertStringContainsString(
            'CHECK ((id > 0))',
            $bulk['orders']['constraints']['shared_name']
        );
    }

    public function testSharedColumnNameStaysScopedToItsTable(): void
    {
        $bulk = $this->adapter->getBulkTableSchema($this->connection, ['users', 'orders']);

        $this->assertSame('"name" text NOT NULL', $bulk['users']['columns']['name']);
        $this->assertSame('"name" varchar(50)',   $bulk['orders']['columns']['name']);
    }

    public function testConstraintBackedIndexesAreExcludedPerTable(): void
    {
        $bulk = $this->adapter->getBulkTableSchema($this->connection, self::TABLES);

        // Plain indexes survive...
        $this->assertArrayHasKey('users_email_idx',   $bulk['users']['keys']);
        $this->assertArrayHasKey('users_partial_idx', $bulk['users']['keys']);
        $this->assertArrayHasKey('orders_total_idx',  $bulk['orders']['keys']);

        // ...while PK/UNIQUE-backed indexes are rendered as constraints instead.
        $this->assertArrayNotHasKey('users_pkey2',       $bulk['users']['keys']);
        $this->assertArrayNotHasKey('parent_code_uniq',  $bulk['parent']['keys']);
        $this->assertArrayNotHasKey('orders_total_uniq', $bulk['orders']['keys']);
    }

    public function testTableWithoutIndexesOrConstraintsResolvesCleanly(): void
    {
        $bulk = $this->adapter->getBulkTableSchema($this->connection, self::TABLES);

        $this->assertSame(['a', 'b'], array_keys($bulk['plain']['columns']));
        $this->assertSame([], $bulk['plain']['keys']);
        $this->assertSame([], $bulk['plain']['constraints']);
    }

    // ── Column rendering against real catalog data ────────────────────────

    public function testRendersIdentityGeneratedAndTypedColumns(): void
    {
        $bulk = $this->adapter->getBulkTableSchema($this->connection, ['users', 'orders']);
        $users  = $bulk['users']['columns'];
        $orders = $bulk['orders']['columns'];

        $this->assertSame('"id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY', $users['id']);
        $this->assertSame('"email" varchar(255)', $users['email']);
        $this->assertSame('"balance" numeric(12,2) DEFAULT 0.00', $users['balance']);
        $this->assertSame('"tags" _text', $users['tags']);
        $this->assertStringStartsWith('"created_at" timestamptz(3)', $users['created_at']);

        // The generation expression is whatever the server deparses it to, and
        // that text is not guaranteed stable across major versions — assert the
        // structure DBDiff builds around it rather than Postgres' own wording.
        $this->assertStringStartsWith('"line" numeric(10,2) GENERATED ALWAYS AS (', $orders['line']);
        $this->assertStringEndsWith(') STORED', $orders['line']);
        $this->assertMatchesRegularExpression('/\btotal\b.*\*.*\bqty\b/', $orders['line']);
    }

    /**
     * The FK/UNIQUE/PK query reads pg_catalog directly and maps catalog codes
     * back to the strings information_schema would have produced (issue #184).
     * This pins every arm of that mapping, since a wrong code silently emits
     * the wrong referential action into a migration.
     */
    public function testForeignKeyActionsAndModifiersRenderCorrectly(): void
    {
        $this->connection->unprepared(<<<'SQL'
            CREATE TABLE fk_target (a integer, b integer, PRIMARY KEY (a, b));
            CREATE TABLE fk_src (
                id integer PRIMARY KEY,
                cas_a integer, cas_b integer,
                sn_a integer,  sn_b integer,
                sd_a integer DEFAULT 0, sd_b integer DEFAULT 0,
                rs_a integer,  rs_b integer,
                full_a integer, full_b integer,
                def_a integer, def_b integer,
                imm_a integer, imm_b integer,
                CONSTRAINT fk_cascade FOREIGN KEY (cas_a, cas_b) REFERENCES fk_target (a, b)
                    ON UPDATE CASCADE ON DELETE CASCADE,
                CONSTRAINT fk_setnull FOREIGN KEY (sn_a, sn_b) REFERENCES fk_target (a, b)
                    ON DELETE SET NULL,
                CONSTRAINT fk_setdefault FOREIGN KEY (sd_a, sd_b) REFERENCES fk_target (a, b)
                    ON DELETE SET DEFAULT,
                CONSTRAINT fk_restrict FOREIGN KEY (rs_a, rs_b) REFERENCES fk_target (a, b)
                    ON UPDATE RESTRICT ON DELETE RESTRICT,
                CONSTRAINT fk_matchfull FOREIGN KEY (full_a, full_b) REFERENCES fk_target (a, b)
                    MATCH FULL,
                CONSTRAINT fk_deferred FOREIGN KEY (def_a, def_b) REFERENCES fk_target (a, b)
                    DEFERRABLE INITIALLY DEFERRED,
                CONSTRAINT fk_immediate FOREIGN KEY (imm_a, imm_b) REFERENCES fk_target (a, b)
                    DEFERRABLE INITIALLY IMMEDIATE
            );
            ALTER TABLE fk_src ADD CONSTRAINT fk_unvalidated
                FOREIGN KEY (cas_a, cas_b) REFERENCES fk_target (a, b) NOT VALID;
        SQL);

        $c = $this->adapter->getBulkTableSchema($this->connection, ['fk_src'])['fk_src']['constraints'];

        // Referential actions
        $this->assertStringEndsWith('ON UPDATE CASCADE ON DELETE CASCADE',       $c['fk_cascade']);
        $this->assertStringEndsWith('ON UPDATE NO ACTION ON DELETE SET NULL',    $c['fk_setnull']);
        $this->assertStringEndsWith('ON UPDATE NO ACTION ON DELETE SET DEFAULT', $c['fk_setdefault']);
        $this->assertStringEndsWith('ON UPDATE RESTRICT ON DELETE RESTRICT',     $c['fk_restrict']);

        // MATCH FULL is emitted; simple match (the default) maps to NONE and
        // must emit nothing at all.
        $this->assertStringContainsString('MATCH FULL', $c['fk_matchfull']);
        $this->assertStringNotContainsString('MATCH', $c['fk_cascade']);

        // Deferrability and validation state
        $this->assertStringEndsWith('DEFERRABLE INITIALLY DEFERRED',  $c['fk_deferred']);
        $this->assertStringEndsWith('DEFERRABLE INITIALLY IMMEDIATE', $c['fk_immediate']);
        $this->assertStringEndsWith('NOT VALID', $c['fk_unvalidated']);

        // Composite key columns appear once each, in ordinal order.
        $this->assertStringContainsString(
            'FOREIGN KEY ("cas_a", "cas_b") REFERENCES "fk_target" ("a")',
            $c['fk_cascade']
        );
    }

    public function testMultiColumnUniqueConstraintListsEachColumnOnce(): void
    {
        $bulk = $this->adapter->getBulkTableSchema($this->connection, ['orders']);
        $this->assertSame(
            'CONSTRAINT "orders_total_uniq" UNIQUE ("id", "total")',
            $bulk['orders']['constraints']['orders_total_uniq']
        );
    }

    // ── Query budget ──────────────────────────────────────────────────────

    public function testQueryCountIsConstantRegardlessOfTableCount(): void
    {
        // The whole point of #165: adding tables must not add round-trips.
        $this->connection->enableQueryLog();

        $this->connection->flushQueryLog();
        $this->adapter->getBulkTableSchema($this->connection, ['users']);
        $oneTable = count($this->connection->getQueryLog());

        $this->connection->flushQueryLog();
        $this->adapter->getBulkTableSchema($this->connection, self::TABLES);
        $allTables = count($this->connection->getQueryLog());

        $this->assertSame(7, $oneTable, 'Expected a fixed 7-query budget per side');
        $this->assertSame($oneTable, $allTables, 'Query count grew with the number of tables');
    }

    public function testBulkIsCheaperThanPerTableFetching(): void
    {
        $this->connection->enableQueryLog();

        $this->connection->flushQueryLog();
        $this->adapter->getBulkTableSchema($this->connection, self::TABLES);
        $batched = count($this->connection->getQueryLog());

        $this->connection->flushQueryLog();
        foreach (self::TABLES as $table) {
            $this->adapter->getTableSchema($this->connection, $table);
        }
        $perTable = count($this->connection->getQueryLog());

        $this->assertLessThan($perTable, $batched);
    }

    public function testEmptyTableListIssuesNoQueries(): void
    {
        $this->connection->enableQueryLog();
        $this->connection->flushQueryLog();

        $this->assertSame([], $this->adapter->getBulkTableSchema($this->connection, []));
        $this->assertCount(0, $this->connection->getQueryLog());
    }

    // ── Pre-scan hash map against a live server ───────────────────────────

    public function testSchemaHashMapCoversAllTablesByDefault(): void
    {
        $hashes = $this->adapter->getSchemaHashMap($this->connection, []);
        foreach (self::TABLES as $table) {
            $this->assertArrayHasKey($table, $hashes);
        }
    }

    public function testSchemaHashMapNarrowsToRequestedTables(): void
    {
        // Key order follows the server's result order, not the request order —
        // callers only ever index this map by table name.
        $hashes = $this->adapter->getSchemaHashMap($this->connection, ['users', 'plain']);
        $keys   = array_keys($hashes);
        sort($keys);
        $this->assertSame(['plain', 'users'], $keys);
    }

    public function testSchemaHashChangesWhenSchemaChanges(): void
    {
        $before = $this->adapter->getSchemaHashMap($this->connection, ['users']);
        $this->connection->unprepared('ALTER TABLE users ADD COLUMN nickname text');
        $after = $this->adapter->getSchemaHashMap($this->connection, ['users']);

        $this->assertNotSame($before['users'], $after['users']);
    }

    public function testSchemaHashIsStableAcrossRepeatCalls(): void
    {
        // A hash that varied between calls would defeat the pre-scan entirely.
        $this->assertSame(
            $this->adapter->getSchemaHashMap($this->connection, self::TABLES),
            $this->adapter->getSchemaHashMap($this->connection, self::TABLES)
        );
    }

    public function testSchemaHashIsUnchangedByPureDataWrites(): void
    {
        $before = $this->adapter->getSchemaHashMap($this->connection, ['orders']);
        $this->connection->unprepared("INSERT INTO orders (id, total, qty) VALUES (1, 5.00, 2)");
        $after = $this->adapter->getSchemaHashMap($this->connection, ['orders']);

        $this->assertSame($before['orders'], $after['orders']);
    }
}
