<?php

/**
 * Column changes PostgreSQL makes with an ALTER of their own rather than a
 * type change, against a live server: identity (issue #236), storage and
 * compression (issue #225), and a column becoming or ceasing to be generated
 * (issue #233). See PostgresRoundTripTestCase for how each case is checked.
 */
class ColumnAttributesRoundTripPostgresTest extends PostgresRoundTripTestCase
{
    protected string $prefix = 'dbdiff_col';

    private const ROWS = 'INSERT INTO t (v) SELECT g FROM generate_series(1, 5) g;';

    /**
     * Where the identity's sequence stands: the next insert must not reuse
     * an id, which restarting the sequence — dropping and re-adding the
     * identity — made it do.
     */
    private function nextId(): callable
    {
        return function (string $db) {
            $pdo = $this->connect($db);
            $pdo->beginTransaction();
            $pdo->exec('INSERT INTO t (v) VALUES (100)');
            $id = $pdo->query('SELECT max(id) FROM t')->fetchColumn();
            $pdo->rollBack();
            return ['next' => (int) $id >= 6];
        };
    }

    /** @return array<string, array{string, string}> */
    public static function identityChanges(): array
    {
        return [
            'kind'    => ['id int GENERATED ALWAYS AS IDENTITY', 'id int GENERATED BY DEFAULT AS IDENTITY'],
            'options' => ['id int GENERATED ALWAYS AS IDENTITY (INCREMENT BY 10 MAXVALUE 100000)',
                          'id int GENERATED ALWAYS AS IDENTITY'],
            'type'    => ['id bigint GENERATED ALWAYS AS IDENTITY', 'id int GENERATED ALWAYS AS IDENTITY'],
            'to'      => ['id int GENERATED BY DEFAULT AS IDENTITY', 'id serial'],
        ];
    }

    /** @dataProvider identityChanges */
    public function testAnIdentityChangeKeepsTheSequenceWhereItIs(string $source, string $target): void
    {
        $case = 'id' . substr(md5($source . $target), 0, 6);
        $up = $this->assertRoundTrip(
            $case,
            "CREATE TABLE t ($source PRIMARY KEY, v int);" . self::ROWS,
            "CREATE TABLE t ($target PRIMARY KEY, v int);" . self::ROWS,
            $this->nextId()
        );
        $this->assertStringNotContainsString('DROP IDENTITY', $up);
    }

    public function testAnIdentityRemovedKeepsTheColumnsValues(): void
    {
        $this->assertRoundTrip(
            'fromid',
            'CREATE TABLE t (id int PRIMARY KEY, v int); INSERT INTO t VALUES (1, 1), (2, 2);',
            'CREATE TABLE t (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, v int); INSERT INTO t (v) VALUES (1), (2);',
            fn(string $db) => $this->rows($db, 'SELECT id, v FROM t ORDER BY id')
        );
    }

    public function testARetypedSerialTakesItsSequenceWithIt(): void
    {
        $this->assertRoundTrip(
            'bigserial',
            'CREATE TABLE t (id bigserial, v int);' . self::ROWS,
            'CREATE TABLE t (id serial, v int);' . self::ROWS,
            fn(string $db) => $this->rows(
                $db,
                "SELECT seqtypid::regtype::text AS type FROM pg_sequence
                  WHERE seqrelid = pg_get_serial_sequence('t', 'id')::regclass"
            )
        );
    }

    public function testStorageAndCompressionAreApplied(): void
    {
        $up = $this->assertRoundTrip(
            'storage',
            'CREATE TABLE t (id int, body text COMPRESSION lz4, blob bytea);
             ALTER TABLE t ALTER COLUMN blob SET STORAGE EXTERNAL;',
            'CREATE TABLE t (id int, body text, blob bytea);',
            fn(string $db) => $this->rows(
                $db,
                "SELECT attname, attstorage, attcompression FROM pg_attribute
                  WHERE attrelid = 't'::regclass AND attnum > 0 ORDER BY attnum"
            )
        );
        $this->assertStringContainsString('SET COMPRESSION lz4', $up);
        $this->assertStringContainsString('SET STORAGE EXTERNAL', $up);
    }

    public function testARetypedColumnKeepsItsStorageAndCompression(): void
    {
        // ALTER COLUMN ... TYPE resets both to the new type's defaults.
        $this->assertRoundTrip(
            'retype',
            'CREATE TABLE t (id int, body text COMPRESSION lz4);
             ALTER TABLE t ALTER COLUMN body SET STORAGE EXTERNAL;',
            'CREATE TABLE t (id int, body varchar(200));',
            fn(string $db) => $this->rows(
                $db,
                "SELECT attstorage, attcompression FROM pg_attribute WHERE attrelid = 't'::regclass AND attname = 'body'"
            )
        );
    }

    public function testANewColumnWithNonDefaultStorage(): void
    {
        $this->assertRoundTrip(
            'newcol',
            'CREATE TABLE t (id int, body text); ALTER TABLE t ALTER COLUMN body SET STORAGE MAIN;',
            'CREATE TABLE t (id int);'
        );
    }

    /** @return array<string, array{string, string}> */
    public static function generatedDirections(): array
    {
        return [
            'plain to generated' => ['b int GENERATED ALWAYS AS (a * 2) STORED', 'b int'],
            'generated to plain' => ['b int', 'b int GENERATED ALWAYS AS (a * 2) STORED'],
            'new expression'     => ['b int GENERATED ALWAYS AS (a * 3) STORED', 'b int GENERATED ALWAYS AS (a * 2) STORED'],
        ];
    }

    /** @dataProvider generatedDirections */
    public function testAColumnBecomingOrCeasingToBeGenerated(string $source, string $target): void
    {
        $case = 'gen' . substr(md5($source . $target), 0, 6);
        $this->assertRoundTrip(
            $case,
            "CREATE TABLE t (id int PRIMARY KEY, a int, $source); CREATE INDEX t_b ON t (b);",
            "CREATE TABLE t (id int PRIMARY KEY, a int, $target); CREATE INDEX t_b ON t (b);"
        );
    }
}
