<?php namespace DBDiff\Migration\Format;

/**
 * Laravel migration format.
 *
 * Produces a single PHP file with an anonymous class extending
 * Illuminate\Database\Migrations\Migration.  The generated up() and down()
 * methods use DB::unprepared() to execute the raw SQL.
 *
 * File names follow the Laravel convention:
 *   YYYY_MM_DD_HHMMSS_description.php
 *
 * render() returns an array so the caller can write the file with the correct name:
 *   [ '2026_03_03_120000_create_users.php' => '<?php ...' ]
 *
 * NOTE: The generated SQL is intentionally left as raw SQL inside DB::unprepared()
 * calls.  You are encouraged to review and, where appropriate, replace them with
 * Illuminate Schema Builder calls for proper cross-database portability.
 */
class LaravelFormat implements FormatInterface
{
    public function render(string $up, string $down, string $description = '', string $version = ''): array
    {
        $version     = $version    ?: date('YmdHis');
        $description = $description ?: 'migration';
        $slug        = $this->slugify($description);

        // Laravel file naming: YYYY_MM_DD_HHMMSS_slug.php
        $laravelVersion = preg_replace(
            '/(\d{4})(\d{2})(\d{2})(\d{6})/',
            '$1_$2_$3_$4',
            $version
        );
        $fileName = "{$laravelVersion}_{$slug}.php";

        // Embed SQL as PHP single-quoted strings with proper escaping.
        // This avoids any heredoc indentation issues across PHP versions.
        $upLiteral   = $this->toPhpString(trim($up)   ?: '-- (empty)');
        $downLiteral = $this->toPhpString(trim($down) ?: '-- (empty)');

        $content = <<<PHP
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * DBDiff-generated Laravel migration.
 *
 * Version     : {$version}
 * Description : {$description}
 * Generated   : {$this->timestamp()}
 *
 * NOTE: SQL was auto-generated by DBDiff. Review before committing.
 * Consider converting DB::unprepared() calls to Schema Builder methods
 * for better cross-database portability and rollback safety.
 */
return new class extends Migration
{
    public function up(): void
    {
        DB::unprepared(
            {$upLiteral}
        );
    }

    public function down(): void
    {
        DB::unprepared(
            {$downLiteral}
        );
    }
};
PHP;

        return [$fileName => $content];
    }

    public function getExtension(): string
    {
        return 'php';
    }

    public function getLabel(): string
    {
        return 'Laravel Migration (up()/down() class)';
    }

    private function slugify(string $text): string
    {
        return strtolower(trim(preg_replace('/[^a-zA-Z0-9]+/', '_', $text), '_'));
    }

    /**
     * Wrap SQL in a PHP single-quoted string literal, spanning multiple lines.
     * Each line of SQL becomes a separate concatenated string so the generated
     * file stays readable and avoids any heredoc indentation concerns.
     */
    private function toPhpString(string $sql): string
    {
        $lines  = explode("\n", $sql);
        $parts  = [];

        foreach ($lines as $line) {
            // Escape backslashes and single quotes for PHP single-quoted strings
            $escaped = str_replace(['\\', "'"], ['\\\\', "\\'"], $line);
            $parts[] = "'{$escaped}'";
        }

        if (count($parts) === 1) {
            return $parts[0];
        }

        // Concatenate with . "\n" between lines for readability
        $glue = ' . "\n"' . "\n            . ";
        return implode($glue, $parts);
    }

    private function timestamp(): string
    {
        return date('Y-m-d H:i:s');
    }
}
