<?php namespace DBDiff\Migration\Format;

use DBDiff\Exceptions\FSException;
use Illuminate\Filesystem\Filesystem;
use Illuminate\View\Compilers\BladeCompiler;

/**
 * Output through a template of your own: `--template=path` (or `template:` in
 * the config file), with `{{ $up }}` and `{{ $down }}` where the SQL goes —
 * Simple DB Migrate's `templates/simple-db-migrate.tmpl`, for example.
 *
 * 2.x applied it; 3.x documented it but wrote native SQL regardless, because
 * only the older entry point ever read the template.
 */
final class TemplateFormat implements FormatInterface
{
    public function __construct(private string $template, private bool $nocomments = false)
    {
        if (!is_file($template)) {
            throw new FSException("Template file not found: {$template}");
        }
    }

    public function render(string $up, string $down, string $description = '', string $version = ''): string
    {
        $compiled = (new BladeCompiler(new Filesystem, sys_get_temp_dir()))
            ->compileString(' ?>' . file_get_contents($this->template));
        $content = (static function (string $__compiled, string $up, string $down): string {
            ob_start();
            eval($__compiled);
            return (string) ob_get_clean();
        })($compiled, trim($up, "\n"), trim($down, "\n"));

        return $this->nocomments
            ? $content
            : "# Generated by DBDiff\n# On " . date('m/d/Y h:i:s a') . "\n\n" . $content;
    }

    public function getExtension(): string
    {
        return 'sql';
    }

    public function getLabel(): string
    {
        return 'Template (' . basename($this->template) . ')';
    }
}
