<?php

namespace DBDiff\Tests\Unit;

use PHPUnit\Framework\TestCase;
use DBDiff\SQLGen\Dialect\PostgresDialect;

class PostgresDialectTest extends TestCase
{
    private PostgresDialect $dialect;

    protected function setUp(): void
    {
        $this->dialect = new PostgresDialect();
    }

    // ── Quoting ───────────────────────────────────────────────────────────

    public function testQuoteSimpleName(): void
    {
        $this->assertSame('"users"', $this->dialect->quote('users'));
    }

    public function testQuoteHyphenatedName(): void
    {
        $this->assertSame('"my-table"', $this->dialect->quote('my-table'));
    }

    public function testQuoteNameWithDoubleQuote(): void
    {
        $this->assertSame('"name""with""quotes"', $this->dialect->quote('name"with"quotes'));
    }

    public function testQuoteNameWithSpaces(): void
    {
        $this->assertSame('"table name"', $this->dialect->quote('table name'));
    }

    // ── Driver ────────────────────────────────────────────────────────────

    public function testGetDriver(): void
    {
        $this->assertSame('pgsql', $this->dialect->getDriver());
    }

    public function testIsNotMySQLOnly(): void
    {
        $this->assertFalse($this->dialect->isMySQLOnly());
    }

    // ── DROP TRIGGER requires ON table ────────────────────────────────────

    public function testDropTriggerIncludesOnTable(): void
    {
        $sql = $this->dialect->dropTrigger('trg_audit', 'orders');
        $this->assertSame('DROP TRIGGER IF EXISTS "trg_audit" ON "orders";', $sql);
    }

    public function testDropTriggerQuotesSpecialNames(): void
    {
        $sql = $this->dialect->dropTrigger('my-trigger', 'my-table');
        $this->assertSame('DROP TRIGGER IF EXISTS "my-trigger" ON "my-table";', $sql);
    }

    // ── DROP INDEX (schema-level, no ALTER TABLE) ─────────────────────────

    public function testDropIndexNoAlterTable(): void
    {
        $sql = $this->dialect->dropIndex('orders', 'idx_orders_user');
        $this->assertSame('DROP INDEX "idx_orders_user";', $sql);
    }

    // ── ADD/DROP COLUMN ───────────────────────────────────────────────────

    public function testAddColumn(): void
    {
        $sql = $this->dialect->addColumn('users', '"phone" varchar(20) DEFAULT NULL');
        $this->assertSame('ALTER TABLE "users" ADD COLUMN "phone" varchar(20) DEFAULT NULL;', $sql);
    }

    public function testDropColumn(): void
    {
        $sql = $this->dialect->dropColumn('users', 'phone');
        $this->assertSame('ALTER TABLE "users" DROP COLUMN "phone" CASCADE;', $sql);
    }

    // ── Column changes with an ALTER of their own ─────────────────────────

    public function testAnIdentityKindAndOptionsChangeInPlace(): void
    {
        $this->assertSame(
            "ALTER TABLE \"t\" ALTER COLUMN \"id\" SET GENERATED BY DEFAULT;\n"
            . 'ALTER TABLE "t" ALTER COLUMN "id" SET INCREMENT BY 10;',
            $this->dialect->changeColumn(
                't', 'id',
                '"id" integer GENERATED BY DEFAULT AS IDENTITY (INCREMENT BY 10)',
                '"id" integer GENERATED ALWAYS AS IDENTITY'
            )
        );
    }

    public function testAnIdentityRetypedKeepsTheIdentity(): void
    {
        $this->assertSame(
            'ALTER TABLE "t" ALTER COLUMN "id" TYPE bigint;',
            $this->dialect->changeColumn('t', 'id', '"id" bigint GENERATED ALWAYS AS IDENTITY', '"id" integer GENERATED ALWAYS AS IDENTITY')
        );
    }

    public function testAPlainColumnBecomingAnIdentityStartsPastItsValues(): void
    {
        $sql = $this->dialect->changeColumn('t', 'id', '"id" integer NOT NULL GENERATED ALWAYS AS IDENTITY', '"id" integer NOT NULL');

        $this->assertStringContainsString('ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY;', $sql);
        $this->assertStringContainsString("SELECT setval(pg_get_serial_sequence('\"t\"', 'id'), COALESCE(MAX(\"id\"), 0) + 1, false) FROM \"t\";", $sql);
        $this->assertStringNotContainsString('DROP IDENTITY', $sql);
    }

    public function testASerialColumnBecomingAnIdentityLosesItsSequenceFirst(): void
    {
        $this->assertSame(
            "ALTER TABLE \"t\" ALTER COLUMN \"id\" DROP DEFAULT;\n"
            . "DROP SEQUENCE IF EXISTS public.t_id_seq;\n"
            . "ALTER TABLE \"t\" ALTER COLUMN \"id\" ADD GENERATED BY DEFAULT AS IDENTITY;\n"
            . "SELECT setval(pg_get_serial_sequence('\"t\"', 'id'), COALESCE(MAX(\"id\"), 0) + 1, false) FROM \"t\";",
            $this->dialect->withSerialSequence('public.t_id_seq')
                ->changeColumn('t', 'id', '"id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY', '"id" serial')
        );
    }

    public function testAnIdentityBecomingSerialGetsAnOwnedSequence(): void
    {
        $this->assertSame(
            "ALTER TABLE \"t\" ALTER COLUMN \"id\" DROP IDENTITY;\n"
            . "CREATE SEQUENCE IF NOT EXISTS public.t_id_seq AS bigint;\n"
            . "ALTER SEQUENCE public.t_id_seq OWNED BY \"t\".\"id\";\n"
            . "ALTER TABLE \"t\" ALTER COLUMN \"id\" SET DEFAULT nextval('public.t_id_seq'::regclass);\n"
            . "SELECT setval('public.t_id_seq', COALESCE(MAX(\"id\"), 0) + 1, false) FROM \"t\";",
            $this->dialect->withSerialSequence('public.t_id_seq')
                ->changeColumn('t', 'id', '"id" bigserial', '"id" bigint NOT NULL GENERATED ALWAYS AS IDENTITY')
        );
    }

    public function testARetypedSerialTakesItsSequenceWithIt(): void
    {
        $this->assertSame(
            "ALTER TABLE \"t\" ALTER COLUMN \"id\" TYPE bigint;\n"
            . 'ALTER SEQUENCE public.t_id_seq AS bigint;',
            $this->dialect->withSerialSequence('public.t_id_seq')->changeColumn('t', 'id', '"id" bigserial', '"id" serial')
        );
    }

    public function testASerialSequenceNameIsGuessedWhenNotRead(): void
    {
        $this->assertStringContainsString(
            'DROP SEQUENCE IF EXISTS "t_id_seq";',
            $this->dialect->changeColumn('t', 'id', '"id" integer NOT NULL', '"id" serial')
        );
    }

    public function testCompressionIsSetAgainAfterATypeChange(): void
    {
        $this->assertSame(
            "ALTER TABLE \"t\" ALTER COLUMN \"b\" TYPE character varying(20);\n"
            . 'ALTER TABLE "t" ALTER COLUMN "b" SET COMPRESSION lz4;',
            $this->dialect->changeColumn('t', 'b', '"b" character varying(20) COMPRESSION lz4', '"b" text COMPRESSION lz4')
        );
        $this->assertSame(
            'ALTER TABLE "t" ALTER COLUMN "b" SET COMPRESSION default;',
            $this->dialect->changeColumn('t', 'b', '"b" text', '"b" text COMPRESSION lz4')
        );
    }

    public function testAGeneratedColumnBecomingPlainKeepsItsValues(): void
    {
        $this->assertSame(
            'ALTER TABLE "t" ALTER COLUMN "g" DROP EXPRESSION;',
            $this->dialect->changeColumn('t', 'g', '"g" integer', '"g" integer GENERATED ALWAYS AS ((a * 2)) STORED')
        );
    }
}
