<?php

namespace Tests\Unit;

use DBDiff\SQLGen\Dialect\PostgresDialect;
use PHPUnit\Framework\TestCase;

/**
 * What the PostgreSQL dialect emits for a changed column.
 *
 * Two properties, both of which a migration's runnability depends on:
 *
 *   - `ALTER COLUMN ... TYPE` appears only when the type changes. PostgreSQL
 *     refuses even a same-type TYPE on a column a view or policy reads, so
 *     restating it turned a default change into a migration that failed.
 *   - A conversion from a string type carries `USING col::type`, which
 *     PostgreSQL will not supply itself — `user_id text` to `uuid` failed with
 *     "cannot be cast automatically" — and nothing else does, since an
 *     explicit cast can succeed where the implicit one rightly refuses.
 */
class PostgresColumnTypeChangeTest extends TestCase
{
    private function change(string $old, string $new): string
    {
        return (new PostgresDialect())->changeColumn('t', 'c', $new, $old);
    }

    public function testADefaultChangeDoesNotRestateTheType(): void
    {
        $this->assertSame(
            'ALTER TABLE "t" ALTER COLUMN "c" SET DEFAULT 5;',
            $this->change('"c" numeric(10,2) DEFAULT 1', '"c" numeric(10,2) DEFAULT 5')
        );
    }

    public function testANullabilityChangeDoesNotRestateTheType(): void
    {
        $this->assertSame(
            'ALTER TABLE "t" ALTER COLUMN "c" SET NOT NULL;',
            $this->change('"c" integer', '"c" integer NOT NULL')
        );
    }

    public function testATypeChangeIsEmitted(): void
    {
        $this->assertSame(
            'ALTER TABLE "t" ALTER COLUMN "c" TYPE numeric(12,2);',
            $this->change('"c" numeric(10,2)', '"c" numeric(12,2)')
        );
    }

    public function testAnUnknownPreviousDefinitionStillStatesTheType(): void
    {
        $sql = (new PostgresDialect())->changeColumn('t', 'c', '"c" integer', '');
        $this->assertStringContainsString('ALTER COLUMN "c" TYPE integer', $sql);
    }

    public function testTextToUuidCarriesAUsingCast(): void
    {
        $this->assertSame(
            'ALTER TABLE "t" ALTER COLUMN "c" TYPE uuid USING "c"::uuid;',
            $this->change('"c" text', '"c" uuid')
        );
    }

    /** @return array<string, array{string, string}> */
    public static function stringSources(): array
    {
        return [
            'varchar to integer' => ['"c" character varying(20)', 'integer'],
            'text to jsonb'      => ['"c" text', 'jsonb'],
            'text to boolean'    => ['"c" text', 'boolean'],
            'text[] to uuid[]'   => ['"c" text[]', 'uuid[]'],
        ];
    }

    /** @dataProvider stringSources */
    public function testEveryStringSourceCarriesAUsingCast(string $old, string $newType): void
    {
        $this->assertStringContainsString(
            "TYPE $newType USING \"c\"::$newType;",
            $this->change($old, "\"c\" $newType")
        );
    }

    public function testNoUsingCastTowardsAStringType(): void
    {
        // An explicit cast to varchar(n) truncates silently where the
        // assignment cast refuses with "value too long".
        $this->assertSame(
            'ALTER TABLE "t" ALTER COLUMN "c" TYPE character varying(10);',
            $this->change('"c" text', '"c" character varying(10)')
        );
        $this->assertStringNotContainsString('USING', $this->change('"c" uuid', '"c" text'));
    }

    public function testNoUsingCastBetweenOtherTypes(): void
    {
        $this->assertStringNotContainsString('USING', $this->change('"c" integer', '"c" bigint'));
    }

    public function testChangesColumnTypeReportsOnlyARealChange(): void
    {
        $this->assertFalse(PostgresDialect::changesColumnType('"c" integer DEFAULT 1', '"c" integer DEFAULT 2'));
        $this->assertFalse(PostgresDialect::changesColumnType('"c" integer', '"c" integer NOT NULL'));
        $this->assertTrue(PostgresDialect::changesColumnType('"c" integer', '"c" bigint'));
    }

    public function testAnIdentityColumnDoesNotRestateAnUnchangedType(): void
    {
        $sql = $this->change(
            '"c" bigint GENERATED BY DEFAULT AS IDENTITY',
            '"c" bigint GENERATED ALWAYS AS IDENTITY'
        );
        $this->assertStringNotContainsString('TYPE', str_replace('IDENTITY', '', $sql));
    }
}
