name: Lint GitHub Actions workflows

on:
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/**.yml'
      - '.github/workflows/**.yaml'
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/**.yml'
      - '.github/workflows/**.yaml'

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run actionlint
        run: |
          bash <(curl -s https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color
